### ISSUE TITLE
Errors when generating query Q10 in config_small

### ISSUE THREAD

**Issue by momo54** [GDD-Nantes/FedShop#59]
root@docker-desktop:/FedShop# python rsfb/query.py create-workload-value-selection experiments/bsbm/benchmark/generation/q10/value_selection.sparql experiments/bsbm/benchmark/generation/q10/value_selection.csv experiments/bsbm/benchmark/generation/q10/workload_value_selection.csv 2
DEBUG:query.py:
Traceback (most recent call last):
  File "rsfb/query.py", line 1036, in <module>
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "rsfb/query.py", line 1032, in create_workload_value_selection
    result.sample(n_instances).to_csv(workload_value_selection, index=False)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5446, in sample
    sampled_indices = sample.sample(obj_len, size, replace, weights, rs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/sample.py", line 150, in sample
    return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(
  File "mtrand.pyx", line 909, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

**Comment by momo54** [comment]
looks to work fine now..

**Comment by momo54** [comment]
Fixed in last version
